version: '2'
services:
  db:
    build: ./db
    container_name: db
  web:
    build: ./web
    container_name: web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
